server:
  port: 8001
spring:
  application:
    name: PROVIDER-DEPT
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud1
    username: root
    password: 19723dd
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
  cloud:
    config:
      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka,http://127.0.0.1:7003/eureka
mybatis:
  type-aliases-package: com.deng.springcloudapi.domain;
---
server:
  port: 8001
spring:
  application:
    name: PROVIDER-DEPT
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2
    username: root
    password: 19723dd
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
  cloud:
    config:
      profile: test
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka,http://127.0.0.1:7003/eureka
mybatis:
  type-aliases-package: com.deng.springcloudapi.domain;
