server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka,http://127.0.0.1:7003/eureka
    register-with-eureka: false
spring:
  cloud:
    config:
      profile: dev
---
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka,http://127.0.0.1:7003/eureka
    register-with-eureka: false
spring:
  cloud:
    config:
      profile: test